/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TanstackQueryRouteImport } from './routes/tanstack-query'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as PokedexDemoRouteImport } from './routes/pokedex-demo'
import { Route as LearnMoreRouteImport } from './routes/learn-more'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as FrontendStatesRouteImport } from './routes/frontend-states'
import { Route as DemoTimeRouteImport } from './routes/demo-time'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'

const TanstackQueryRoute = TanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexDemoRoute = PokedexDemoRouteImport.update({
  id: '/pokedex-demo',
  path: '/pokedex-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMoreRoute = LearnMoreRouteImport.update({
  id: '/learn-more',
  path: '/learn-more',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendStatesRoute = FrontendStatesRouteImport.update({
  id: '/frontend-states',
  path: '/frontend-states',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTimeRoute = DemoTimeRouteImport.update({
  id: '/demo-time',
  path: '/demo-time',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/demo-time': typeof DemoTimeRoute
  '/frontend-states': typeof FrontendStatesRoute
  '/intro': typeof IntroRoute
  '/learn-more': typeof LearnMoreRoute
  '/pokedex-demo': typeof PokedexDemoRoute
  '/questions': typeof QuestionsRoute
  '/tanstack-query': typeof TanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/demo-time': typeof DemoTimeRoute
  '/frontend-states': typeof FrontendStatesRoute
  '/intro': typeof IntroRoute
  '/learn-more': typeof LearnMoreRoute
  '/pokedex-demo': typeof PokedexDemoRoute
  '/questions': typeof QuestionsRoute
  '/tanstack-query': typeof TanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/demo-time': typeof DemoTimeRoute
  '/frontend-states': typeof FrontendStatesRoute
  '/intro': typeof IntroRoute
  '/learn-more': typeof LearnMoreRoute
  '/pokedex-demo': typeof PokedexDemoRoute
  '/questions': typeof QuestionsRoute
  '/tanstack-query': typeof TanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/demo-time'
    | '/frontend-states'
    | '/intro'
    | '/learn-more'
    | '/pokedex-demo'
    | '/questions'
    | '/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/demo-time'
    | '/frontend-states'
    | '/intro'
    | '/learn-more'
    | '/pokedex-demo'
    | '/questions'
    | '/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/demo-time'
    | '/frontend-states'
    | '/intro'
    | '/learn-more'
    | '/pokedex-demo'
    | '/questions'
    | '/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  DemoTimeRoute: typeof DemoTimeRoute
  FrontendStatesRoute: typeof FrontendStatesRoute
  IntroRoute: typeof IntroRoute
  LearnMoreRoute: typeof LearnMoreRoute
  PokedexDemoRoute: typeof PokedexDemoRoute
  QuestionsRoute: typeof QuestionsRoute
  TanstackQueryRoute: typeof TanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanstack-query': {
      id: '/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/tanstack-query'
      preLoaderRoute: typeof TanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex-demo': {
      id: '/pokedex-demo'
      path: '/pokedex-demo'
      fullPath: '/pokedex-demo'
      preLoaderRoute: typeof PokedexDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-more': {
      id: '/learn-more'
      path: '/learn-more'
      fullPath: '/learn-more'
      preLoaderRoute: typeof LearnMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend-states': {
      id: '/frontend-states'
      path: '/frontend-states'
      fullPath: '/frontend-states'
      preLoaderRoute: typeof FrontendStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-time': {
      id: '/demo-time'
      path: '/demo-time'
      fullPath: '/demo-time'
      preLoaderRoute: typeof DemoTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  DemoTimeRoute: DemoTimeRoute,
  FrontendStatesRoute: FrontendStatesRoute,
  IntroRoute: IntroRoute,
  LearnMoreRoute: LearnMoreRoute,
  PokedexDemoRoute: PokedexDemoRoute,
  QuestionsRoute: QuestionsRoute,
  TanstackQueryRoute: TanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
