/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TanstackQueryImport } from './routes/tanstack-query'
import { Route as QuestionsImport } from './routes/questions'
import { Route as PokedexDemoImport } from './routes/pokedex-demo'
import { Route as LearnMoreImport } from './routes/learn-more'
import { Route as IntroImport } from './routes/intro'
import { Route as FrontendStatesImport } from './routes/frontend-states'
import { Route as DemoTimeImport } from './routes/demo-time'
import { Route as AboutMeImport } from './routes/about-me'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TanstackQueryRoute = TanstackQueryImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const QuestionsRoute = QuestionsImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRoute,
} as any)

const PokedexDemoRoute = PokedexDemoImport.update({
  id: '/pokedex-demo',
  path: '/pokedex-demo',
  getParentRoute: () => rootRoute,
} as any)

const LearnMoreRoute = LearnMoreImport.update({
  id: '/learn-more',
  path: '/learn-more',
  getParentRoute: () => rootRoute,
} as any)

const IntroRoute = IntroImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRoute,
} as any)

const FrontendStatesRoute = FrontendStatesImport.update({
  id: '/frontend-states',
  path: '/frontend-states',
  getParentRoute: () => rootRoute,
} as any)

const DemoTimeRoute = DemoTimeImport.update({
  id: '/demo-time',
  path: '/demo-time',
  getParentRoute: () => rootRoute,
} as any)

const AboutMeRoute = AboutMeImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeImport
      parentRoute: typeof rootRoute
    }
    '/demo-time': {
      id: '/demo-time'
      path: '/demo-time'
      fullPath: '/demo-time'
      preLoaderRoute: typeof DemoTimeImport
      parentRoute: typeof rootRoute
    }
    '/frontend-states': {
      id: '/frontend-states'
      path: '/frontend-states'
      fullPath: '/frontend-states'
      preLoaderRoute: typeof FrontendStatesImport
      parentRoute: typeof rootRoute
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroImport
      parentRoute: typeof rootRoute
    }
    '/learn-more': {
      id: '/learn-more'
      path: '/learn-more'
      fullPath: '/learn-more'
      preLoaderRoute: typeof LearnMoreImport
      parentRoute: typeof rootRoute
    }
    '/pokedex-demo': {
      id: '/pokedex-demo'
      path: '/pokedex-demo'
      fullPath: '/pokedex-demo'
      preLoaderRoute: typeof PokedexDemoImport
      parentRoute: typeof rootRoute
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsImport
      parentRoute: typeof rootRoute
    }
    '/tanstack-query': {
      id: '/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/tanstack-query'
      preLoaderRoute: typeof TanstackQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/demo-time': typeof DemoTimeRoute
  '/frontend-states': typeof FrontendStatesRoute
  '/intro': typeof IntroRoute
  '/learn-more': typeof LearnMoreRoute
  '/pokedex-demo': typeof PokedexDemoRoute
  '/questions': typeof QuestionsRoute
  '/tanstack-query': typeof TanstackQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/demo-time': typeof DemoTimeRoute
  '/frontend-states': typeof FrontendStatesRoute
  '/intro': typeof IntroRoute
  '/learn-more': typeof LearnMoreRoute
  '/pokedex-demo': typeof PokedexDemoRoute
  '/questions': typeof QuestionsRoute
  '/tanstack-query': typeof TanstackQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/demo-time': typeof DemoTimeRoute
  '/frontend-states': typeof FrontendStatesRoute
  '/intro': typeof IntroRoute
  '/learn-more': typeof LearnMoreRoute
  '/pokedex-demo': typeof PokedexDemoRoute
  '/questions': typeof QuestionsRoute
  '/tanstack-query': typeof TanstackQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/demo-time'
    | '/frontend-states'
    | '/intro'
    | '/learn-more'
    | '/pokedex-demo'
    | '/questions'
    | '/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/demo-time'
    | '/frontend-states'
    | '/intro'
    | '/learn-more'
    | '/pokedex-demo'
    | '/questions'
    | '/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/demo-time'
    | '/frontend-states'
    | '/intro'
    | '/learn-more'
    | '/pokedex-demo'
    | '/questions'
    | '/tanstack-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  DemoTimeRoute: typeof DemoTimeRoute
  FrontendStatesRoute: typeof FrontendStatesRoute
  IntroRoute: typeof IntroRoute
  LearnMoreRoute: typeof LearnMoreRoute
  PokedexDemoRoute: typeof PokedexDemoRoute
  QuestionsRoute: typeof QuestionsRoute
  TanstackQueryRoute: typeof TanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  DemoTimeRoute: DemoTimeRoute,
  FrontendStatesRoute: FrontendStatesRoute,
  IntroRoute: IntroRoute,
  LearnMoreRoute: LearnMoreRoute,
  PokedexDemoRoute: PokedexDemoRoute,
  QuestionsRoute: QuestionsRoute,
  TanstackQueryRoute: TanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-me",
        "/demo-time",
        "/frontend-states",
        "/intro",
        "/learn-more",
        "/pokedex-demo",
        "/questions",
        "/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about-me": {
      "filePath": "about-me.tsx"
    },
    "/demo-time": {
      "filePath": "demo-time.tsx"
    },
    "/frontend-states": {
      "filePath": "frontend-states.tsx"
    },
    "/intro": {
      "filePath": "intro.tsx"
    },
    "/learn-more": {
      "filePath": "learn-more.tsx"
    },
    "/pokedex-demo": {
      "filePath": "pokedex-demo.tsx"
    },
    "/questions": {
      "filePath": "questions.tsx"
    },
    "/tanstack-query": {
      "filePath": "tanstack-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
